### ISSUE TITLE
ish?

### ISSUE THREAD

**Issue by F-Unction** [gamerhat18/vs-code-mobile#1]
So what should I do to install code-server in ish.

**Comment by thecmdrunner** [comment]
The `oneliner.sh` does have iSH support, would be great if you run that and post your experience here :) Thanks!

1. Install `curl` if not already installed 
```bash
apk add curl
```

2. Run `oneliner.sh`:
```bash
# using curl
curl -fsSL https://git.io/JRnBZ | bash

# using git
git clone https://github.com/thegamerhat/vs-code-mobile
cd vs-code-mobile
bash oneliner.sh
```

**Comment by F-Unction** [comment]
It doesn't work.
```
iPad-Pro:~/vs-code-mobile# bash oneliner.sh
cat: can't open '/root/.config/code-server/config.yaml': No such file or directory
oneliner.sh: line 68: ): command not found

:: VS Code Mobile

Your System likely isn't Debian/Fedora/Arch, so make sure to install the Node.JS and yarn through your package manager.
After installing, run the following command;

oneliner.sh: line 190: TEXT: command not found

:: Exiting, Bye!
```

**Comment by thecmdrunner** [comment]
So I think a non-root user might be an issue.

Run the following commands in order which will install nodejs and code-server

```bash
apk add nodejs npm yarn

npm install -g code-server
code-server
```

Then visit `http://127.0.0.1:8080` on your iPad, or `http://<ipad-ip-address>:8080` from other device on local network

**Comment by F-Unction** [comment]
I tried, but it requires node 14+, there's no node 14+ build in the app repo.

**Comment by thecmdrunner** [comment]
Perhaps this could help?

https://coder.com/docs/code-server/v3.11.1/install#docker

**Comment by F-Unction** [comment]
Thank you, I will try it later.

**Comment by F-Unction** [comment]
It seems that ish does not support docker.
https://github.com/ish-app/ish/issues/63

**Comment by thecmdrunner** [comment]
Well, then the only option I see possible is to use a slightly older version of code-server. It's very likely that it would run on Node 10+

**Comment by F-Unction** [comment]
Well, thank you.
