### ISSUE TITLE
Invisible Screenshots

### ISSUE THREAD

**Issue by ghost** [gamerhat18/vs-code-mobile#2]
The screenshots you've shared appear to be broken because they're not visible. That makes "STEP 2" impossible.
Please fix it.

**Comment by thecmdrunner** [comment]
Hey! Sorry for the confusion, but actually there's no screenshot available for it, and it is indeed not broken.

The only screenshots there are, are present in the img directory:
https://github.com/thecmdrunner/vs-code-mobile/tree/main/img

Step 2 screenshot was only about termux asking for storage permission like this:

![image](https://user-images.githubusercontent.com/38887390/221828391-f6b34e3e-7a55-4839-81ed-b77dbe1efd6a.png)
